name: Black Code Formatter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Black
        run: pip install black
      - name: Check code formatting with Black
        run: black --check .
